// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztegyiychzotcvschezp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0ZWd5aXljaHpvdGN2c2NoZXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTA1NTQsImV4cCI6MjA3MTkyNjU1NH0.ixFsT6_qUwtbGJLFcM4Y6R7S85uF2ma6YjWJkzeGAR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});